package com.pairshot.core.designsystem

import androidx.compose.ui.graphics.Color

// Light Scheme
val LightBackground = Color(0xFFFAFAFA)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFEEF1F6)
val LightSurfaceContainerHigh = Color(0xFFE6EAF2)
val LightOnSurface = Color(0xFF171B22)
val LightOnSurfaceVariant = Color(0xFF4A5568)
val LightOutline = Color(0xFF7D8AA3)
val LightOutlineVariant = Color(0xFFC6CEDC)
val LightPrimary = Color(0xFF0381FE)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDDE9FF)
val LightOnPrimaryContainer = Color(0xFF0C2F73)
val LightError = Color(0xFFC53A3A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSuccess = Color(0xFF166534)
val LightWarning = Color(0xFFB45309)

// Dark Scheme
val DarkBackground = Color(0xFF080808)
val DarkSurface = Color(0xFF1A1A1F)
val DarkSurfaceContainer = Color(0xFF242428)
val DarkSurfaceContainerHigh = Color(0xFF2E2E34)
val DarkOnSurface = Color(0xFFE9EDF4)
val DarkOnSurfaceVariant = Color(0xFFB3BCC9)
val DarkOutline = Color(0xFF6B6B73)
val DarkOutlineVariant = Color(0xFF3A3A3F)
val DarkPrimary = Color(0xFF3E91FF)
val DarkOnPrimary = Color(0xFF052A66)
val DarkPrimaryContainer = Color(0xFF1B3D83)
val DarkOnPrimaryContainer = Color(0xFFD9E5FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSuccess = Color(0xFF86EFAC)
val DarkWarning = Color(0xFFFFB95C)
